title: Karlos 
#logo: /assets/img/logo.jpg
# email: person@address.com
description: Investigaci칩n, cursos y tutoriales.
favicon: true
#color-scheme: auto
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Indice
    link: ./index.html

  - name: Cursos
    link: ./index.html
    sublist:
      - name: Bioinform치tica
        link: ./index.html#small-image

  - name: Tutoriales
    link: ./index.html
    sublist:
      - name: Arch Linux
        link: ./index.html#small-image

  - name: Investigaci칩n
    link: ./index.html
    sublist:
      - name: Visi칩n artificial
        link: ./index.html#small-image


  - name: Sobre mi
    link: ./another-page.html

platforms:
  - name: Youtube
    icon: <i class="fa-brands fa-youtube"></i>
    link: https://www.youtube.com/channel/UC5eMAkopgQ3y5BMTWSpvyXQ
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: www.linkedin.com/in/karlos-espinoza-b550b2206


