title: Karlos
#logo: /assets/img/logo.jpg
# email: person@address.com
description: Cursos e investigaci贸n.
favicon: true
#color-scheme: auto
color-scheme: dark

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax

sass:
  sass_dir: _sass
  style: compressed

gems: [jekyll-mermaid]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  #- jekyll-mermaid


navigation:
#  - name: Indice
#    link: /index.html

  - name: Cursos
    link: /curso/
    sublist:
      - name: Linux
        link: /curso/linux/
      - name: Python
        link: /curso/python/
      - name: Inteligencia Artificial
        link: /curso/am/ia_udg/
      - name: Aplicaci贸n Web
        link: /curso/webapp/
#        subsublist:
#          - name: Programa
#            link: /curso/ia/programa
#
#  - name: Tutoriales
#    link: ./index.html
#    sublist:
#      - name: Arch Linux
#        link: ./index.html#small-image
#
#  - name: Investigaci贸n
#    link: ./index.html
#    sublist:
#      - name: Visi贸n artificial
#        link: ./index.html#small-image
#
#
#  - name: Sobre mi
#    link: ./another-page.html

platforms:
  - name: Youtube
    icon: <i class="fa-brands fa-youtube"></i>
    link: https://www.youtube.com/channel/UC5eMAkopgQ3y5BMTWSpvyXQ
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: www.linkedin.com/in/karlos-espinoza-b550b2206
  - name: Calendario
    icon: <i class="fa-solid fa-calendar-days"></i>
    link: https://calendar.app.google/tpjjZMEUoCymj3Ex7

#markdown: kramdown
#kramdown:
#  input: GFM
#  hard_wrap: false
#  math_engine: mathjax

