title: Karlos 
#logo: /assets/img/logo.jpg
# email: person@address.com
description: Tutoriales y Cursos.
favicon: true
#color-scheme: auto
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: Youtube
    icon: <i class="fa-brands fa-youtube"></i>
    link: https://www.youtube.com/channel/UC5eMAkopgQ3y5BMTWSpvyXQ
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: www.linkedin.com/in/karlos-espinoza-b550b2206

navigation:
  - name: Indice
    link: ./index.html
  - name: Cursos
    link: ./index.html
    sublist:
      - name: Bioinform√°tica
        link: ./index.html#small-image
  - name: Tutoriales
    link: ./index.html
    sublist:
      - name: Arch Linux
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
